name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deployment-what-if
      uses: Azure/deployment-what-if-action@v1.0.0
      with:
        # Subscription ID
        subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
        # Resource group name
        resourceGroup: rg-slicerushpizza-westeurope
        # ARM template or Bicep file
        templateFile: infra/main.bicep
        # Additional parameters to be applied on the ARM template or Bicep. Multiple parameters should be separated by spaces.
        additionalParameters: 'projectName=slicerushpizza location=westeurope resourceGroupName=rg-slicerushpizza-westeurope'
          

    # - name: Deploy Bicep file
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     #resourceGroupName: ${{ secrets.AZURE_RG }}
    #     template: ./infra/main.bicep
    #     parameters: 'projectName=slicerushpizza location=westeurope'
    #     failOnStdErr: false

